language: cpp

compiler:
  - clang

script:
  - make tests


notifications:
  email:
    recipients:
      - your_ta_email@nyu.edu
      - your_email@nyu.edu
    on_success: always
    on_failure: never
